
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jun 14 20:05:43 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SQ = 36;
  public static final int LBRACKET = 29;
  public static final int CHAR = 53;
  public static final int CONST = 21;
  public static final int NAMESPACE = 27;
  public static final int DOTACCESS = 37;
  public static final int USING = 28;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 24;
  public static final int DECR = 40;
  public static final int INCR = 39;
  public static final int FOR = 25;
  public static final int MINUS = 11;
  public static final int STATIC = 26;
  public static final int RPAREN = 7;
  public static final int AND = 31;
  public static final int LT = 47;
  public static final int RANGE = 14;
  public static final int OR = 32;
  public static final int BOOL = 51;
  public static final int COMMA = 12;
  public static final int CLASS = 17;
  public static final int DIV = 34;
  public static final int GEQ = 46;
  public static final int PLUS = 10;
  public static final int IF = 19;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 30;
  public static final int EQUAL = 8;
  public static final int LAMBDA = 41;
  public static final int NEW = 22;
  public static final int error = 1;
  public static final int MUL = 33;
  public static final int NUMBER = 50;
  public static final int MOD = 35;
  public static final int NEQ = 44;
  public static final int IDENT = 52;
  public static final int BREAK = 18;
  public static final int VOID = 13;
  public static final int EQ = 43;
  public static final int COLON = 38;
  public static final int LBRACE = 3;
  public static final int ELSE = 20;
  public static final int READ = 16;
  public static final int GOTO = 42;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 23;
  public static final int PROG = 2;
  public static final int LEQ = 48;
  public static final int STRING = 49;
  public static final int GT = 45;
  public static final int PRINT = 15;
}

